services:
  gpt-engineer:
    build: .
    volumes:
      - .:/app
    ports:
      - "8009:8000"
    env_file:
      - .env
    networks:
      - my_network

  db:
    image: postgres:13
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge
